# Stage 1: Build
FROM ubuntu:22.04 AS build

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential cmake curl git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN cmake -Bbuild -H. && cmake --build build --target bloomserver

# Stage 2: Runtime only
FROM ubuntu:22.04 AS runtime

WORKDIR /app
COPY --from=build /app/build/bloomserver .

EXPOSE 12345
CMD ["./bloomserver", "12345", "8", "1", "2"]
