FROM node:18-alpine AS base

WORKDIR /usr/src/app

# Install dependencies only once
COPY package*.json ./
RUN npm ci --only=production

# Copy app code
COPY . .

# Set environment
ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "App.js"]
